### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by 01Hamichok10** [ProgerOffline/lis-skins-parser#1]
I'm trying to run the program, I put the following data in search 6 times writes that the received items : 0 and then it breaks.

`{
    "items":[
       {
            "name":"FAMAS | Survivor Z (Factory New)",
            "price_max":1,
            "float_min":0,
            "float_max":1
        }
    ]
}
`

**Comment by progeroffline** [comment]
This is fine. I'm still trying to get back to this project, but it's not finished so it's normal that you have problems using it.
