### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by batilegrand** [ProgerOffline/lis-skins-parser#2]
Hello i'm a complete noob , can you please help me use this parser please .
-is it possible to use it on visual studio code or do i need another program ?
- is the program still working ? any tips on how to configure it please sorry for being a noob

**Comment by progeroffline** [comment]
Hello. The parser is still in work. I'm glad you're interested in it, but I don't have time yet to get it to the point where you can run it from your PC.

**Comment by batilegrand** [comment]
what do you mean please ? it is possible to pay for your time ?

**Comment by progeroffline** [comment]
Yep, we can agree on payment and I will urgently complete the parser to suit your needs. Can we go to messenger?

**Comment by batilegrand** [comment]
yes how do i contact you

**Comment by progeroffline** [comment]
Just send me mail to progeroffline@gmail.com
